language: java
sudo: false
notifications:
  hipchat:
    rooms:
      secure: PxZ7z3mb6p8IqKXy03abwUVFulWZrgO2frVXIVnHX96ElymX1M7Ut772L5BvdyeBBuzumyczhfHxJ8x23ZpcYRc3GRmCflv7pE1ZUBhjfCYjPIWCWO+kCRZBnHnvQ6tSZuGJARWMEWwn5iPdrsF6ElHOf3Xesk7t4p0EahClnogM9bWzmQNPlfp6lbPpuesgQVPM8xzFqBE1CbMhkEuFVz5M1hNjo43L9JVXTm0aXRJiU0PukOMXo+X/1+5VwYmdg0vchfGzViQyu9ev77C5XqsPLhxwQev47rLpLxB9oYjsSzqeIdGqOORFswU5dFWF8JbcIuRBZL0wve0Yv/idgBFuSD1cGu+x4arZg4YOxECDRUrJf3Vee9cK1dUwVzk7eHV61/ucrtd0qcAr75r2hVfshVOVVehHf31Ek+CncJcT76pcmQdumbOYI+c2kAWtJcNeRGYhoBXA9DhOZMmVrvZ0+g91s8EvyzXQauGFqX/hG2Vb852CozZp8kKXePaeM9oNZIJxuvqINuoEuSpJkXEb1LV0QxNYdBc/9DebdfbwHfOkTSgDgd6qQw++4GvcuTb82a+R7MWYkfI9VxdqB7KOdrp03bItoO90Zx2gI/Y3gPqw+yIKqR+RuELOaWN31JMRzK6xawbbVT6PVSPpGcU20yc4I2/AuXkxrqJvJQs=
deploy:
  provider: releases
  api_key:
    secure: EmkkWRmgabN6vJAPCOl2tGlT2sJ4KXbRZwXW4zNtCVXw73dhElTikp8BP8h8pgeIpGYPhcGd7SI0Gg574PYhOJ4xFbc94yNSzLof/Yvfoe9PHfsrBwYOQvWur1nEwAfa2xA3i3AbpGHm1tzxnHcjvP7tZXNcaiCE4c9MvSAeQEb85OXWYTKn+y5hjWztfn5OB0EVWEMb//tT4mGbjN3xXuKKr0UVFRyuOdKIMx4bua30qQ7/Wx+v6ltoXWHxjl7HodUukjc07LMTrGsuON9JVsL4h43cvMaove8U4u8X5Bx474dZKYoqWAYjpa1VjUwSKIIXjAXhZTQdUbkxuOPQiVPIvz9ihypWtO0/2OafbRrBevssgQa4W+0vx5VjjA4WwB3+teL9IddRRbpsEOKgrg3iZjWO76l5d2+ofuFwt9WKO+0KtTei9+iLnBZnJW6Hmcqpzi8mUNGmUTytwdqSum3CcBxVi/B0reJfW8Bf3lmluCbQBzYJdV7uE9T2gc0ijQgMkvL8/xR0/kcYm5I+qhXrS1Z/c9iab4H2g6KEBMd2Is0Jo/8SUYGezgGVNDY9bUqbKjM4uBVJjNxKgzORDE/H/a+QUSZbf3RJcpuFs0n6FQFQPS+LOpPcwmmVgOz0KCcJawxfWV5Ew/aB6A0ruHtGgfNadXS/EUvU6SFDRDs=
  file: build/distributions//xld-github-dynamic-dictionaries-plugin-1.0.2.xldp
  on:
    repo: xebialabs-community/xld-github-dynamic-dictionaries-plugin
    all_branches: true
    tags: true
