language: java
sudo: false
notifications:
  slack:
    secure: Ut08deqPdH46/2c0aS+7ml01rxZ3CzeFvYtziQNu0n0utDEAak9cmSdOAYD6vn3WJs3p9BMuV218uG42iHTDb9XTVv6fAtPpIyUiiB8BcYv4xN0Ax/mrGLIUOD1FaF+sbT30orY1GQAyoEdRWcMgnf+eMJTSIeGK5kq+IB6BvdAMtjafZbpPJ/RNV49b3aWYgy28mRYyVGYANbfQN2oI9iIdiRsdV4q6g3hwR+Uv6KUkZ+sazaZKWQudzG+hzHqJ2WBNtpsgwnwgM1JC0s3UhdvU8bN6vsvd/LoVFUYmy+GCheNl+QeHxRPjGgI3w2K2sYjMt6vpmSIYrVmtKl4g/cviEe8309Z7Ns1LRt84KWIXKdWmGuhwmCUA+XnCrxgAhmhd61IG7D+YG1HBa8TfuWe8DOUheVGGT4yThsU2s9S8WS8zm///zLktSXu2IoAP8Ej//XgvlzweRNVMwOyIkwWGIsTUWaijYglF2cqlbDEKu4dhheo0VeEuRKKCthAyeEoDbrQjQlUlT0I0uh2zLOTI3rNaDnNRkueUcrM8xH/5HUgf/6DGF/0y/ynibc9U4bU3KHaX9lzbjOQpL82zwU5+BMpf2N2BANxEplZcTwS/lBgURVVFzHAuN2MTg6SMux5IEIjSmk2RXXCfP0Hkfbmfo5GssC7nQxxKS1ZLPmc=
deploy:
  provider: releases
  api_key:
    secure: EmkkWRmgabN6vJAPCOl2tGlT2sJ4KXbRZwXW4zNtCVXw73dhElTikp8BP8h8pgeIpGYPhcGd7SI0Gg574PYhOJ4xFbc94yNSzLof/Yvfoe9PHfsrBwYOQvWur1nEwAfa2xA3i3AbpGHm1tzxnHcjvP7tZXNcaiCE4c9MvSAeQEb85OXWYTKn+y5hjWztfn5OB0EVWEMb//tT4mGbjN3xXuKKr0UVFRyuOdKIMx4bua30qQ7/Wx+v6ltoXWHxjl7HodUukjc07LMTrGsuON9JVsL4h43cvMaove8U4u8X5Bx474dZKYoqWAYjpa1VjUwSKIIXjAXhZTQdUbkxuOPQiVPIvz9ihypWtO0/2OafbRrBevssgQa4W+0vx5VjjA4WwB3+teL9IddRRbpsEOKgrg3iZjWO76l5d2+ofuFwt9WKO+0KtTei9+iLnBZnJW6Hmcqpzi8mUNGmUTytwdqSum3CcBxVi/B0reJfW8Bf3lmluCbQBzYJdV7uE9T2gc0ijQgMkvL8/xR0/kcYm5I+qhXrS1Z/c9iab4H2g6KEBMd2Is0Jo/8SUYGezgGVNDY9bUqbKjM4uBVJjNxKgzORDE/H/a+QUSZbf3RJcpuFs0n6FQFQPS+LOpPcwmmVgOz0KCcJawxfWV5Ew/aB6A0ruHtGgfNadXS/EUvU6SFDRDs=
  file: build/distributions//xld-github-dynamic-dictionaries-plugin-1.0.2.xldp
  on:
    repo: xebialabs-community/xld-github-dynamic-dictionaries-plugin
    all_branches: true
    tags: true
